# Generated by Django 3.0 on 2019-12-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitter',
            old_name='tweet_image',
            new_name='twitter_image',
        ),
        migrations.RenameField(
            model_name='twitter',
            old_name='tweet_location',
            new_name='twitter_location',
        ),
        migrations.RenameField(
            model_name='twitter',
            old_name='tweet_text',
            new_name='twitter_text',
        ),
    ]
