# Generated by Django 3.0 on 2020-11-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20191215_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twitter',
            options={'verbose_name_plural': 'Tweets'},
        ),
        migrations.AddField(
            model_name='twitter',
            name='file_name',
            field=models.CharField(default='abc', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
