# Generated by Django 3.0 on 2020-11-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20201103_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter',
            name='tweet_posted',
            field=models.CharField(default='not published', max_length=200),
            preserve_default=False,
        ),
    ]
